// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wBcw9dcxKyU36yfsUviVdG
// Component: kdE_dd2jbPd
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import RoutesDialog from "../../RoutesDialog"; // plasmic-import: DFJFHCaPCd/component

import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_responsive_bb.module.css"; // plasmic-import: wBcw9dcxKyU36yfsUviVdG/projectcss
import sty from "./PlasmicSubscribePage.module.css"; // plasmic-import: kdE_dd2jbPd/css

export type PlasmicSubscribePage__VariantMembers = {};
export type PlasmicSubscribePage__VariantsArgs = {};
type VariantPropType = keyof PlasmicSubscribePage__VariantsArgs;
export const PlasmicSubscribePage__VariantProps = new Array<VariantPropType>();

export type PlasmicSubscribePage__ArgsType = {
  routesDi?: React.ReactNode;
  headerRowA?: React.ReactNode;
};

type ArgPropType = keyof PlasmicSubscribePage__ArgsType;
export const PlasmicSubscribePage__ArgProps = new Array<ArgPropType>(
  "routesDi",
  "headerRowA"
);

export type PlasmicSubscribePage__OverridesType = {
  root?: p.Flex<"div">;
  headerRow?: p.Flex<"div">;
  heroRow?: p.Flex<"div">;
  navRow?: p.Flex<"div">;
  storesRow?: p.Flex<"div">;
  footerRow?: p.Flex<"div">;
  routesDialog?: p.Flex<typeof RoutesDialog>;
};

export interface DefaultSubscribePageProps {
  routesDi?: React.ReactNode;
  headerRowA?: React.ReactNode;
  className?: string;
}

function PlasmicSubscribePage__RenderFunc(props: {
  variants: PlasmicSubscribePage__VariantsArgs;
  args: PlasmicSubscribePage__ArgsType;
  overrides: PlasmicSubscribePage__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__eIlmj)}>
        <div
          data-plasmic-name={"headerRow"}
          data-plasmic-override={overrides.headerRow}
          className={classNames(defaultcss.all, sty.headerRow)}
        >
          <div className={classNames(defaultcss.all, sty.box___5DwIc)}>
            <p.PlasmicSlot defaultContents={null} value={args.headerRowA} />
          </div>
        </div>

        <div
          data-plasmic-name={"heroRow"}
          data-plasmic-override={overrides.heroRow}
          className={classNames(defaultcss.all, sty.heroRow)}
        />

        <div
          data-plasmic-name={"navRow"}
          data-plasmic-override={overrides.navRow}
          className={classNames(defaultcss.all, sty.navRow)}
        />

        <div
          data-plasmic-name={"storesRow"}
          data-plasmic-override={overrides.storesRow}
          className={classNames(defaultcss.all, sty.storesRow)}
        >
          <div className={classNames(defaultcss.all, sty.box__iYxWg)}>
            <div className={classNames(defaultcss.all, sty.box__ttex)}>
              <div className={classNames(defaultcss.all, sty.box__xkOZz)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__q41R
                  )}
                >
                  {"Recibe nuevas marcas en tu buzón"}
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box___4CClO)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__kbjbc
                  )}
                >
                  {
                    "Nuestra newsletter incluye marcas que hacen cosas curiosas, utilizan materiales novedosos o innovan en la fabricación de sus productos"
                  }
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box__vl29Y)}>
                <div className={classNames(defaultcss.all, sty.box__aToF4)}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__pG2N
                    )}
                  >
                    {"Escribe tu email"}
                  </div>
                </div>

                <div className={classNames(defaultcss.all, sty.box__pUhZx)}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__qncQk
                    )}
                  >
                    {"Suscríbete"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div
          data-plasmic-name={"footerRow"}
          data-plasmic-override={overrides.footerRow}
          className={classNames(defaultcss.all, sty.footerRow)}
        />
      </div>

      {false ? (
        <div className={classNames(defaultcss.all, sty.box__xpoU8)}>
          <p.PlasmicSlot
            defaultContents={
              <RoutesDialog
                data-plasmic-name={"routesDialog"}
                data-plasmic-override={overrides.routesDialog}
                className={classNames("__wab_instance", sty.routesDialog)}
              />
            }
            value={args.routesDi}
          />
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerRow",
    "heroRow",
    "navRow",
    "storesRow",
    "footerRow",
    "routesDialog"
  ],

  headerRow: ["headerRow"],
  heroRow: ["heroRow"],
  navRow: ["navRow"],
  storesRow: ["storesRow"],
  footerRow: ["footerRow"],
  routesDialog: ["routesDialog"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerRow: "div";
  heroRow: "div";
  navRow: "div";
  storesRow: "div";
  footerRow: "div";
  routesDialog: typeof RoutesDialog;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSubscribePage__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSubscribePage__VariantsArgs;
    args?: PlasmicSubscribePage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSubscribePage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSubscribePage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSubscribePage__ArgProps,
      internalVariantPropNames: PlasmicSubscribePage__VariantProps
    });

    return PlasmicSubscribePage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSubscribePage";
  } else {
    func.displayName = `PlasmicSubscribePage.${nodeName}`;
  }
  return func;
}

export const PlasmicSubscribePage = Object.assign(
  // Top-level PlasmicSubscribePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerRow: makeNodeComponent("headerRow"),
    heroRow: makeNodeComponent("heroRow"),
    navRow: makeNodeComponent("navRow"),
    storesRow: makeNodeComponent("storesRow"),
    footerRow: makeNodeComponent("footerRow"),
    routesDialog: makeNodeComponent("routesDialog"),

    // Metadata about props expected for PlasmicSubscribePage
    internalVariantProps: PlasmicSubscribePage__VariantProps,
    internalArgProps: PlasmicSubscribePage__ArgProps
  }
);

export default PlasmicSubscribePage;
/* prettier-ignore-end */
