// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicMainPage,
  DefaultMainPageProps
} from "./plasmic/responsive_bb/PlasmicMainPage";
import SearchCard from "./SearchCard"
import BrandCard from "./BrandCard"
import CustomSearchBox from './CustomSearchBox';
import {
  connectStateResults,
  Hits
} from 'react-instantsearch-dom';
// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface MainPageProps extends Omit<DefaultMainPageProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultMainPageProps altogether and have
// total control over the props for your component.
function Hit(props: any) {
  var cat = ""
  if (Array.isArray(props.hit["tags propios"])){
    cat = props.hit["tags propios"][0]
  }else{
    cat = props.hit["tags propios"]
  }
  cat = cat.length < 20 ? cat :  cat.split(",")[0]+"..."
  return <BrandCard 
    brandCardImage={<img alt="brand" style={{maxWidth: "100%", maxHeight: "100%"}} src={props.hit["Image Link"]}/>}
    name={props.hit["title"]}
    category={"#"+ cat}/>
}

function connectedResult(te: (searchTerm: string)=>void, {searchState, searchResults, children}: any){
  if(searchResults===null || searchResults["query"]===""){
    return (<SearchCard searchTerm={"Zapatos"} onClick={te}/>)
  }else{
    return (<div><Hits hitComponent={Hit} /></div>)
  }
}

interface MainPageProps extends DefaultMainPageProps {
  searchMethod:(searchTerm: string)=>void,
  searchTerm:string
}

function MainPage({searchMethod,searchTerm, ...props}: MainPageProps) {
  const  Results = connectStateResults(({ searchState, searchResults, children}) => {return connectedResult(searchMethod, {searchState, searchResults, children})});
  return (
        <PlasmicMainPage 
          routesDi={null} 
          storesResults={<Results/>}
          heroRowSearchbox={<CustomSearchBox defaultSearch={searchTerm}/>}
          {...props} />);
}

export default MainPage;



